### ISSUE TITLE
Cache results of external APIs

### ISSUE THREAD

**Issue by fabiopelosin** [CocoaPods/feeds.cocoapods.org#260]
The star counts and any call to externals API (future search.cocoapods.org) could be cached according to their freshness. An approach could be:

- 1 min for Pods added in the last 12h
- 3 mins for Pods added in the last 24h
- 9 mins for Pods added in the last 48h

Is something like Memcached suitable for the task?

**Comment by segiddins** [comment]
I think we can close this out now.
